backend:
  name: github
  repo: oumoussa98/gridsome-personal-website

media_folder: "src/assets/posts-images"
public_folder: "/posts-images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "image", name: "img", widget: "image"}
      # - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date", dateFormat: "DD.MMMM.YYYY"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}